# FROM registry.cn-shanghai.aliyuncs.com/ootb/deepbase:10.1-cudnn7-devel-ubuntu18.04
FROM ootb/deepbase:10.1-cudnn7-devel-ubuntu18.04

COPY pip.conf /root/.pip/pip.conf
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . /deepcode


RUN groupadd -g ${GROUPS:-1000} deepcode && \
        useradd -u ${UID:-1000} -g ${GROUPS:-1000} -ms /bin/bash  deepcode 
RUN chown -R deepcode:deepcode /deepcode

USER deepcode
WORKDIR /deepcode
